# https://hub.docker.com/_/mongo
# https://hub.docker.com/_/mongo-express
# https://hub.docker.com/r/mongoclient/mongoclient
# https://hub.docker.com/_/adminer
# https://hub.docker.com/_/mysql
# https://hub.docker.com/_/postgres

# $ sudo docker-compose up -d
# $ sudo docker-compose ps
# $ sudo docker-compose ps -a
# $ sudo docker-compose restart
# $ sudo docker-compose down
# $ sudo docker-compose down
# $ sudo docker-compose down -v
# $ sudo docker-compose up -d --remove-orphans

# $ sudo docker network ls

# $ sudo docker rm -f CONTAINER_ID
# $ sudo docker rmi -f IMAGE_ID

# $ sudo docker inspect CONTAINER_NAME_OR_ID


version: '3'

services:
  
    galhardoapp_mysql:
        image: mysql:latest
        container_name: galhardoapp_mysql
        environment:
          MYSQL_ROOT_PASSWORD: "root"
        ports:
          - "3306:3306"
        volumes:
          - mysql-data:/var/lib/mysql
        networks:
          - galhardoapp_network

    galhardoapp_postgres:
        image: postgres
        container_name: galhardoapp_postgres
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardoapp_network


    # ADMINER GUI FOR MYSQL AND POSTGRES
    # MYSQL username: root | password: root | server: galhardoapp_mysql
    # POSTGRE username: postgres | password: root |server: galhardoapp_postgres
    galhardoapp_adminer:
        image: adminer
        container_name: galhardoapp_adminer
        ports:
          - "8080:8080"
        networks:
          - galhardoapp_network


    galhardoapp_mongodb:
        image: mongo:4
        container_name: galhardoapp_mongodb
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        volumes:
          - mongo-data:/data/db


networks: 
  galhardoapp_network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data:
  postgres-data:
