# https://imasters.com.br/banco-de-dados/mysql-adminer-docker-compose-montando-rapidamente-um-ambiente-para-uso
# $ sudo docker-compose up -d
# $ sudo docker network ls 
# $ sudo docker-compose ps
# Server: mysql-database
# sudo docker inspect CONTAINER_NAME_OR_ID | grep '"IPAddress"' | head -n 1

version: '3'

services:
  mysql-database:
    image: mysql
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge