# https://renatogroffe.medium.com/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89
# https://imasters.com.br/banco-de-dados/mysql-adminer-docker-compose-montando-rapidamente-um-ambiente-para-uso
# https://renatogroffe.medium.com/mongodb-mongo-express-docker-compose-montando-rapidamente-um-ambiente-para-uso-824f25ca6957

# https://hub.docker.com/_/mongo
# https://hub.docker.com/_/mongo-express
# https://hub.docker.com/r/mongoclient/mongoclient
# https://hub.docker.com/_/adminer
# https://hub.docker.com/_/mysql
# https://hub.docker.com/_/postgres


# $ sudo docker-compose up -d
# $ sudo docker network ls 
# $ sudo docker-compose ps
# $ sudo docker-compose ps -a
# $ sudo docker-compose restart
# $ sudo docker-compose down
# $ sudo docker rm -f CONTAINER_ID
# $ sudo docker rmi -f IMAGE_ID
# $ sudo docker-compose up -d --remove-orphans

# $ sudo docker inspect CONTAINER_NAME_OR_ID | grep '"IPAddress"' | head -n 1
# $ docker inspect --format '{{ .NetworkSettings.IPAddress }}' container_name_or_id


version: '3'

services:
  
  
    # MYSQL DB
    galhardoapp_mysql:
        image: mysql:latest
        container_name: galhardoapp_mysql
        environment:
          MYSQL_ROOT_PASSWORD: "root"
        ports:
          - "3306:3306"
        #volumes:
        #  - /home/alex/Desktop/galhardo-app/backups/backuos/mysql:/var/www/html
        networks:
          - galhardoapp_network


    # POSTGRES DB
    galhardoapp_postgres:
        image: postgres
        container_name: galhardoapp_postgres
        environment:
            POSTGRES_PASSWORD: "root"
        ports:
            - "15432:5432"
        #volumes:
            #  - /home/alex/Desktop/galhardo-app:/var/lib/postgresql/data
        networks:
            - galhardoapp_network


    # ADMINER GUI FOR MYSQL AND POSTGRES
    # MYSQL username: root | server: galhardoapp_mysql
    # POSTGRE username: postgres | server: galhardoapp_postgres
    galhardoapp_adminer:
        image: adminer
        container_name: galhardoapp_adminer
        ports:
          - "8080:8080"
        networks:
          - galhardoapp_network


    galhardoapp_mongodb:
        image: mongo:latest
        container_name: galhardoapp_mongodb
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
          - 27017:27017
        #volumes:
        #  - mongo-data:/data/db


networks: 
  galhardoapp_network:
    driver: bridge

#volumes:
#  mongo-data:
