# https://hub.docker.com/_/adminer
# https://hub.docker.com/_/mysql

# $ sudo docker-compose up -d
# $ sudo docker-compose ps
# $ sudo docker-compose ps -a
# $ sudo docker-compose restart
# $ sudo docker-compose down
# $ sudo docker-compose down
# $ sudo docker-compose down -v
# $ sudo docker-compose up -d --remove-orphans

# $ sudo docker network ls

# $ sudo docker rm -f CONTAINER_ID
# $ sudo docker rmi -f IMAGE_ID

# $ sudo docker inspect CONTAINER_NAME_OR_ID

# sudo kill -9 $(sudo lsof -t -i:3000)

version: '3'

services:
  
    galhardoapp_mysql:
        image: mysql:latest
        container_name: galhardoapp_mysql
        environment:
          MYSQL_ROOT_PASSWORD: "root"
        ports:
          - "3306:3306"
        volumes:
          - mysql-data:/var/lib/mysql
        networks:
          - galhardoapp_network

    # ADMINER GUI FOR MYSQL
    # http://localhost:8080
    # MYSQL username: root | password: root | server: galhardoapp_mysql
    galhardoapp_adminer:
        image: adminer
        container_name: galhardoapp_adminer
        ports:
          - "8080:8080"
        networks:
          - galhardoapp_network

networks: 
  galhardoapp_network:
    driver: bridge

volumes:
  mysql-data:
